//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        public Land()
        {
            this.Raumschiffe = new HashSet<Raumschiff>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Laenderkennzeichen { get; set; }
    
        public virtual ICollection<Raumschiff> Raumschiffe { get; set; }
    }
}
