//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spektralklasse
    {
        public Spektralklasse()
        {
            this.Himmelskoerper = new HashSet<Himmelskoerper>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Farbe { get; set; }
        public double Tmin { get; set; }
        public double Tmax { get; set; }
        public double Masse_Hauptreihenstern_in_Sonnenmassen { get; set; }
    
        public virtual ICollection<Himmelskoerper> Himmelskoerper { get; set; }
    }
}
