//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sterne_Planeten_Monde
    {
        public double Aequatordurchmesser_in_km { get; set; }
        public double Polardurchmesser_in_km { get; set; }
        public double Oberflaechentemperatur_in_K { get; set; }
        public double Rotationsperiode_in_Stunden { get; set; }
        public double Fallbeschleunigung_in_meter_pro_sec { get; set; }
        public double Rotationsachsenneigung_in_Grad { get; set; }
        public int HimmelskoerperID { get; set; }
    
        public virtual Himmelskoerper Himmelskoerper { get; set; }
    }
}
