//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Kepler.EF60
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlSammlung
    {
        public int ID { get; set; }
        public string Kurzbeschreibung { get; set; }
        public string Url { get; set; }
        public EnumUrlTypen UrlTyp { get; set; }
        public int Himmelskoerper_ID { get; set; }
    
        public virtual Himmelskoerper Himmelskoerper { get; set; }
    }
}
