//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.225
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.1.
// 
namespace mkoIt.Xhtml.Woc {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mkoit.de/WocMetaFile.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.mkoit.de/WocMetaFile.xsd", IsNullable=false)]
    public partial class WocMetaFile {
        
        private string wocGuidField;
        
        private string wocPathField;
        
        private string wocTitleField;
        
        private string wocDescriptionField;
        
        private System.DateTime wocCreatedField;
        
        private string wocAuthorField;
        
        private string wocMadeInDNSField;
        
        /// <remarks/>
        public string WocGuid {
            get {
                return this.wocGuidField;
            }
            set {
                this.wocGuidField = value;
            }
        }
        
        /// <remarks/>
        public string WocPath {
            get {
                return this.wocPathField;
            }
            set {
                this.wocPathField = value;
            }
        }
        
        /// <remarks/>
        public string WocTitle {
            get {
                return this.wocTitleField;
            }
            set {
                this.wocTitleField = value;
            }
        }
        
        /// <remarks/>
        public string WocDescription {
            get {
                return this.wocDescriptionField;
            }
            set {
                this.wocDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime WocCreated {
            get {
                return this.wocCreatedField;
            }
            set {
                this.wocCreatedField = value;
            }
        }
        
        /// <remarks/>
        public string WocAuthor {
            get {
                return this.wocAuthorField;
            }
            set {
                this.wocAuthorField = value;
            }
        }
        
        /// <remarks/>
        public string WocMadeInDNS {
            get {
                return this.wocMadeInDNSField;
            }
            set {
                this.wocMadeInDNSField = value;
            }
        }
    }
}
